### ISSUE TITLE
Raspberry PI B+ wifi

### ISSUE THREAD

**Issue by totoantibes** [rkaczorek/astroberry-server#10] opened 2018-12-26 02:25 UTC
i believe WLAN on pi3B+ and Mate 16.04 are not compatible. I tried to mod the replicant conf file but does not work. I can only have the ethernet working

**Comment by rkaczorek** [comment] 2018-12-27 21:40
There was an issue with astroberry_vap script. RPi revision was inproperly detected. Replace /usr/local/bin/astroberry_vap with the [latest version](https://raw.githubusercontent.com/rkaczorek/astroberry-server/master/scripts/astroberry_vap). If it's ok please close the issue

**Closed** 2019-01-13 18:09 UTC

**Comment by totoantibes** [comment] 2019-01-16 11:58
Hi i just installed that new script but i believe the issue remains. Probably there is a misunderstanding on the issue altogether: my problem is that the on board WIFI module is not detectedwhatsoever by Mate 16.04. I had to buy a USB wifi module and install the drivers manually. At this time I am not even needing the VAP feature since I want my Pi to join my existing Home Network. I was able to configure it with the supplicant_conf file

**Comment by rkaczorek** [comment] 2019-01-16 13:15
I can't reproduce this issue on none of my RPi 3B+. Are you sure you have genuine RPi? What is the output of the following command:
`grep Revision /proc/cpuinfo |awk -F: '{print $2}'|sed 's/\ //'`

**Comment by totoantibes** [comment] 2019-01-16 14:58
pretty sure it is genuine, in any case here is the output of the command: a01041

**Comment by rkaczorek** [comment] 2019-01-16 15:02
Revision a01041 is Raspberry Pi 2B. It's not going to work. The system is designed for 3B and 3B+
Take a look at [Raspberry Pi revision codes](https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md) (bottom of the page).

**Comment by totoantibes** [comment] 2019-01-16 15:24
good catch. I have 2 pi laying around (2b and 3b+)and I guess i mistook the old one for the new one.
