### ISSUE TITLE
Can't get pre-built image to work 

### ISSUE THREAD

**Issue by cplonski** [rkaczorek/astroberry-server#95] opened 2020-08-26 05:50 UTC
I downloaded the pre-built, burnt to a SanDisk 64GB micro sd card, using a 2GB raspberry pi 4 on first boot it flashes something quickly about not being able to expand the filesystem and unrecognized flash, then it reboots and directly to a kernel panic. What kinds of sd cards are supported? The standard raspian image works fine on this card.  

In frustration, I download the code and installed, but it's missing much of the needed apps/data/configs to make it work right.

**Comment by rkaczorek** [comment] 2020-08-26 09:25
Is it duplicate of #94 ?

**Comment by cplonski** [comment] 2020-08-26 12:13
I replied with a screen shot in #94

**Closed** 2020-09-07 21:55 UTC
Labels: bug
